package entidades;

// Generated 15-oct-2012 13:40:25 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Accesorios generated by hbm2java
 */
public class Accesorios implements java.io.Serializable {

	private Integer ref;
	private Proveedores proveedores;
	private String nombre;
	private float precioCompra;
	private float pvp;
	private int idAlbaran;
	private String stock;
	private Set ventases = new HashSet(0);
	private Set ofertases = new HashSet(0);
	private Set pedidoses = new HashSet(0);
	private Set alquilereses = new HashSet(0);

	public Accesorios() {
	}

	public Accesorios(Proveedores proveedores, String nombre,
			float precioCompra, float pvp, int idAlbaran, String stock) {
		this.proveedores = proveedores;
		this.nombre = nombre;
		this.precioCompra = precioCompra;
		this.pvp = pvp;
		this.idAlbaran = idAlbaran;
		this.stock = stock;
	}

	public Accesorios(Proveedores proveedores, String nombre,
			float precioCompra, float pvp, int idAlbaran, String stock,
			Set ventases, Set ofertases, Set pedidoses, Set alquilereses) {
		this.proveedores = proveedores;
		this.nombre = nombre;
		this.precioCompra = precioCompra;
		this.pvp = pvp;
		this.idAlbaran = idAlbaran;
		this.stock = stock;
		this.ventases = ventases;
		this.ofertases = ofertases;
		this.pedidoses = pedidoses;
		this.alquilereses = alquilereses;
	}

	public Integer getRef() {
		return this.ref;
	}

	public void setRef(Integer ref) {
		this.ref = ref;
	}

	public Proveedores getProveedores() {
		return this.proveedores;
	}

	public void setProveedores(Proveedores proveedores) {
		this.proveedores = proveedores;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public float getPrecioCompra() {
		return this.precioCompra;
	}

	public void setPrecioCompra(float precioCompra) {
		this.precioCompra = precioCompra;
	}

	public float getPvp() {
		return this.pvp;
	}

	public void setPvp(float pvp) {
		this.pvp = pvp;
	}

	public int getIdAlbaran() {
		return this.idAlbaran;
	}

	public void setIdAlbaran(int idAlbaran) {
		this.idAlbaran = idAlbaran;
	}

	public String getStock() {
		return this.stock;
	}

	public void setStock(String stock) {
		this.stock = stock;
	}

	public Set getVentases() {
		return this.ventases;
	}

	public void setVentases(Set ventases) {
		this.ventases = ventases;
	}

	public Set getOfertases() {
		return this.ofertases;
	}

	public void setOfertases(Set ofertases) {
		this.ofertases = ofertases;
	}

	public Set getPedidoses() {
		return this.pedidoses;
	}

	public void setPedidoses(Set pedidoses) {
		this.pedidoses = pedidoses;
	}

	public Set getAlquilereses() {
		return this.alquilereses;
	}

	public void setAlquilereses(Set alquilereses) {
		this.alquilereses = alquilereses;
	}

}
