package entidades;

// Generated 15-oct-2012 13:40:25 by Hibernate Tools 3.4.0.CR1

/**
 * Alquileres generated by hbm2java
 */
public class Alquileres implements java.io.Serializable {

	private Integer idAlquiler;
	private Socio socio;
	private Accesorios accesorios;
	private String fechaInicio;
	private String fechaDevolucionAlquiler;

	public Alquileres() {
	}

	public Alquileres(Socio socio, Accesorios accesorios, String fechaInicio,
			String fechaDevolucionAlquiler) {
		this.socio = socio;
		this.accesorios = accesorios;
		this.fechaInicio = fechaInicio;
		this.fechaDevolucionAlquiler = fechaDevolucionAlquiler;
	}

	public Integer getIdAlquiler() {
		return this.idAlquiler;
	}

	public void setIdAlquiler(Integer idAlquiler) {
		this.idAlquiler = idAlquiler;
	}

	public Socio getSocio() {
		return this.socio;
	}

	public void setSocio(Socio socio) {
		this.socio = socio;
	}

	public Accesorios getAccesorios() {
		return this.accesorios;
	}

	public void setAccesorios(Accesorios accesorios) {
		this.accesorios = accesorios;
	}

	public String getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(String fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	public String getFechaDevolucionAlquiler() {
		return this.fechaDevolucionAlquiler;
	}

	public void setFechaDevolucionAlquiler(String fechaDevolucionAlquiler) {
		this.fechaDevolucionAlquiler = fechaDevolucionAlquiler;
	}

}
