package entidades;

// Generated 15-oct-2012 13:40:25 by Hibernate Tools 3.4.0.CR1

/**
 * Clasificacion generated by hbm2java
 */
public class Clasificacion implements java.io.Serializable {

	private Integer id;
	private Socio socio;
	private int puntuacion;
	private String nombre;

	public Clasificacion() {
	}

	public Clasificacion(Socio socio, int puntuacion) {
		this.socio = socio;
		this.puntuacion = puntuacion;
	}

	public Clasificacion(Socio socio, int puntuacion, String nombre) {
		this.socio = socio;
		this.puntuacion = puntuacion;
		this.nombre = nombre;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Socio getSocio() {
		return this.socio;
	}

	public void setSocio(Socio socio) {
		this.socio = socio;
	}

	public int getPuntuacion() {
		return this.puntuacion;
	}

	public void setPuntuacion(int puntuacion) {
		this.puntuacion = puntuacion;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
