package entidades;

// Generated 13-oct-2012 1:52:26 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Empleados generated by hbm2java
 */
public class Empleados implements java.io.Serializable {

	private String dniEmp;
	private String nombre;
	private String apellidos;
	private String direccion;
	private int telefono;
	private String poblacion;
	private String nus;
	private int cp;
	private String cc;
	private byte[] foto;
	private Set usuarios = new HashSet(0);
	private Set pedidoses = new HashSet(0);
	private Set ventaAlquilers = new HashSet(0);
	private Set reservases = new HashSet(0);

	public Empleados() {
	}

	public Empleados(String dniEmp, String nombre, String apellidos,
			String direccion, int telefono, String poblacion, String nus,
			int cp, String cc, byte[] foto) {
		this.dniEmp = dniEmp;
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.direccion = direccion;
		this.telefono = telefono;
		this.poblacion = poblacion;
		this.nus = nus;
		this.cp = cp;
		this.cc = cc;
		this.foto = foto;
	}

	public Empleados(String dniEmp, String nombre, String apellidos,
			String direccion, int telefono, String poblacion, String nus,
			int cp, String cc, byte[] foto, Set usuarios, Set pedidoses,
			Set ventaAlquilers, Set reservases) {
		this.dniEmp = dniEmp;
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.direccion = direccion;
		this.telefono = telefono;
		this.poblacion = poblacion;
		this.nus = nus;
		this.cp = cp;
		this.cc = cc;
		this.foto = foto;
		this.usuarios = usuarios;
		this.pedidoses = pedidoses;
		this.ventaAlquilers = ventaAlquilers;
		this.reservases = reservases;
	}

	public String getDniEmp() {
		return this.dniEmp;
	}

	public void setDniEmp(String dniEmp) {
		this.dniEmp = dniEmp;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public int getTelefono() {
		return this.telefono;
	}

	public void setTelefono(int telefono) {
		this.telefono = telefono;
	}

	public String getPoblacion() {
		return this.poblacion;
	}

	public void setPoblacion(String poblacion) {
		this.poblacion = poblacion;
	}

	public String getNus() {
		return this.nus;
	}

	public void setNus(String nus) {
		this.nus = nus;
	}

	public int getCp() {
		return this.cp;
	}

	public void setCp(int cp) {
		this.cp = cp;
	}

	public String getCc() {
		return this.cc;
	}

	public void setCc(String cc) {
		this.cc = cc;
	}

	public byte[] getFoto() {
		return this.foto;
	}

	public void setFoto(byte[] foto) {
		this.foto = foto;
	}

	public Set getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set usuarios) {
		this.usuarios = usuarios;
	}

	public Set getPedidoses() {
		return this.pedidoses;
	}

	public void setPedidoses(Set pedidoses) {
		this.pedidoses = pedidoses;
	}

	public Set getVentaAlquilers() {
		return this.ventaAlquilers;
	}

	public void setVentaAlquilers(Set ventaAlquilers) {
		this.ventaAlquilers = ventaAlquilers;
	}

	public Set getReservases() {
		return this.reservases;
	}

	public void setReservases(Set reservases) {
		this.reservases = reservases;
	}

}
