package entidades;

// Generated 15-oct-2012 13:40:25 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Ofertas generated by hbm2java
 */
public class Ofertas implements java.io.Serializable {

	private Integer idOferta;
	private Accesorios accesorios;
	private String tipo;
	private float descuento;
	private Date fechainicio;
	private Date fechafin;

	public Ofertas() {
	}

	public Ofertas(Accesorios accesorios, String tipo, float descuento,
			Date fechainicio, Date fechafin) {
		this.accesorios = accesorios;
		this.tipo = tipo;
		this.descuento = descuento;
		this.fechainicio = fechainicio;
		this.fechafin = fechafin;
	}

	public Integer getIdOferta() {
		return this.idOferta;
	}

	public void setIdOferta(Integer idOferta) {
		this.idOferta = idOferta;
	}

	public Accesorios getAccesorios() {
		return this.accesorios;
	}

	public void setAccesorios(Accesorios accesorios) {
		this.accesorios = accesorios;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public float getDescuento() {
		return this.descuento;
	}

	public void setDescuento(float descuento) {
		this.descuento = descuento;
	}

	public Date getFechainicio() {
		return this.fechainicio;
	}

	public void setFechainicio(Date fechainicio) {
		this.fechainicio = fechainicio;
	}

	public Date getFechafin() {
		return this.fechafin;
	}

	public void setFechafin(Date fechafin) {
		this.fechafin = fechafin;
	}

}
