package entidades;

// Generated 15-oct-2012 13:40:25 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Partida generated by hbm2java
 */
public class Partida implements java.io.Serializable {

	private Integer id;
	private int pista;
	private Date fecha;
	private Set puntuacions = new HashSet(0);

	public Partida() {
	}

	public Partida(int pista, Date fecha) {
		this.pista = pista;
		this.fecha = fecha;
	}

	public Partida(int pista, Date fecha, Set puntuacions) {
		this.pista = pista;
		this.fecha = fecha;
		this.puntuacions = puntuacions;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getPista() {
		return this.pista;
	}

	public void setPista(int pista) {
		this.pista = pista;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Set getPuntuacions() {
		return this.puntuacions;
	}

	public void setPuntuacions(Set puntuacions) {
		this.puntuacions = puntuacions;
	}

}
