package entidades;

// Generated 13-oct-2012 1:52:26 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Pistas generated by hbm2java
 */
public class Pistas implements java.io.Serializable {

	private Integer id;
	private byte ocupada;
	private Set reservases = new HashSet(0);
	private Set partidas = new HashSet(0);

	public Pistas() {
	}

	public Pistas(byte ocupada) {
		this.ocupada = ocupada;
	}

	public Pistas(byte ocupada, Set reservases, Set partidas) {
		this.ocupada = ocupada;
		this.reservases = reservases;
		this.partidas = partidas;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public byte getOcupada() {
		return this.ocupada;
	}

	public void setOcupada(byte ocupada) {
		this.ocupada = ocupada;
	}

	public Set getReservases() {
		return this.reservases;
	}

	public void setReservases(Set reservases) {
		this.reservases = reservases;
	}

	public Set getPartidas() {
		return this.partidas;
	}

	public void setPartidas(Set partidas) {
		this.partidas = partidas;
	}

}
