package entidades;

// Generated 15-oct-2012 13:40:25 by Hibernate Tools 3.4.0.CR1

/**
 * PuntuacionId generated by hbm2java
 */
public class PuntuacionId implements java.io.Serializable {

	private int id;
	private int idCliente;
	private int puntuacion;

	public PuntuacionId() {
	}

	public PuntuacionId(int id, int idCliente, int puntuacion) {
		this.id = id;
		this.idCliente = idCliente;
		this.puntuacion = puntuacion;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getIdCliente() {
		return this.idCliente;
	}

	public void setIdCliente(int idCliente) {
		this.idCliente = idCliente;
	}

	public int getPuntuacion() {
		return this.puntuacion;
	}

	public void setPuntuacion(int puntuacion) {
		this.puntuacion = puntuacion;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PuntuacionId))
			return false;
		PuntuacionId castOther = (PuntuacionId) other;

		return (this.getId() == castOther.getId())
				&& (this.getIdCliente() == castOther.getIdCliente())
				&& (this.getPuntuacion() == castOther.getPuntuacion());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + this.getIdCliente();
		result = 37 * result + this.getPuntuacion();
		return result;
	}

}
