package entidades;

// Generated 15-oct-2012 13:40:25 by Hibernate Tools 3.4.0.CR1

/**
 * Puntuacion generated by hbm2java
 */
public class Puntuacion implements java.io.Serializable {

	private PuntuacionId id;
	private Socio socio;
	private Partida partida;
	private String nombre;

	public Puntuacion() {
	}

	public Puntuacion(PuntuacionId id, Socio socio, Partida partida,
			String nombre) {
		this.id = id;
		this.socio = socio;
		this.partida = partida;
		this.nombre = nombre;
	}

	public PuntuacionId getId() {
		return this.id;
	}

	public void setId(PuntuacionId id) {
		this.id = id;
	}

	public Socio getSocio() {
		return this.socio;
	}

	public void setSocio(Socio socio) {
		this.socio = socio;
	}

	public Partida getPartida() {
		return this.partida;
	}

	public void setPartida(Partida partida) {
		this.partida = partida;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
