package entidades;

// Generated 13-oct-2012 1:52:26 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Socio generated by hbm2java
 */
public class Socio implements java.io.Serializable {

	private Integer nsocio;
	private String dni;
	private String nombre;
	private String apellido1;
	private String apellido2;
	private Integer telefono;
	private String direccion;
	private String poblacion;
	private byte[] foto;
	private String correo;
	private Integer cuentaCorriente;
	private Set reservases = new HashSet(0);
	private Set puntuacions = new HashSet(0);
	private Set clasificacions = new HashSet(0);
	private Set usuarios = new HashSet(0);

	public Socio() {
	}

	public Socio(String dni, String nombre, String apellido1, String apellido2) {
		this.dni = dni;
		this.nombre = nombre;
		this.apellido1 = apellido1;
		this.apellido2 = apellido2;
	}

	public Socio(String dni, String nombre, String apellido1, String apellido2,
			Integer telefono, String direccion, String poblacion, byte[] foto,
			String correo, Integer cuentaCorriente, Set reservases,
			Set puntuacions, Set clasificacions, Set usuarios) {
		this.dni = dni;
		this.nombre = nombre;
		this.apellido1 = apellido1;
		this.apellido2 = apellido2;
		this.telefono = telefono;
		this.direccion = direccion;
		this.poblacion = poblacion;
		this.foto = foto;
		this.correo = correo;
		this.cuentaCorriente = cuentaCorriente;
		this.reservases = reservases;
		this.puntuacions = puntuacions;
		this.clasificacions = clasificacions;
		this.usuarios = usuarios;
	}

	public Integer getNsocio() {
		return this.nsocio;
	}

	public void setNsocio(Integer nsocio) {
		this.nsocio = nsocio;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellido1() {
		return this.apellido1;
	}

	public void setApellido1(String apellido1) {
		this.apellido1 = apellido1;
	}

	public String getApellido2() {
		return this.apellido2;
	}

	public void setApellido2(String apellido2) {
		this.apellido2 = apellido2;
	}

	public Integer getTelefono() {
		return this.telefono;
	}

	public void setTelefono(Integer telefono) {
		this.telefono = telefono;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getPoblacion() {
		return this.poblacion;
	}

	public void setPoblacion(String poblacion) {
		this.poblacion = poblacion;
	}

	public byte[] getFoto() {
		return this.foto;
	}

	public void setFoto(byte[] foto) {
		this.foto = foto;
	}

	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	public Integer getCuentaCorriente() {
		return this.cuentaCorriente;
	}

	public void setCuentaCorriente(Integer cuentaCorriente) {
		this.cuentaCorriente = cuentaCorriente;
	}

	public Set getReservases() {
		return this.reservases;
	}

	public void setReservases(Set reservases) {
		this.reservases = reservases;
	}

	public Set getPuntuacions() {
		return this.puntuacions;
	}

	public void setPuntuacions(Set puntuacions) {
		this.puntuacions = puntuacions;
	}

	public Set getClasificacions() {
		return this.clasificacions;
	}

	public void setClasificacions(Set clasificacions) {
		this.clasificacions = clasificacions;
	}

	public Set getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set usuarios) {
		this.usuarios = usuarios;
	}

}
