package entidades;

// Generated 13-oct-2012 1:52:26 by Hibernate Tools 3.4.0.CR1

/**
 * UsuarioId generated by hbm2java
 */
public class UsuarioId implements java.io.Serializable {

	private int id;
	private String user;

	public UsuarioId() {
	}

	public UsuarioId(int id, String user) {
		this.id = id;
		this.user = user;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getUser() {
		return this.user;
	}

	public void setUser(String user) {
		this.user = user;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsuarioId))
			return false;
		UsuarioId castOther = (UsuarioId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getUser() == castOther.getUser()) || (this.getUser() != null
						&& castOther.getUser() != null && this.getUser()
						.equals(castOther.getUser())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result
				+ (getUser() == null ? 0 : this.getUser().hashCode());
		return result;
	}

}
