package entidades;

// Generated 15-oct-2012 13:40:25 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Ventas generated by hbm2java
 */
public class Ventas implements java.io.Serializable {

	private Integer id;
	private Empleados empleados;
	private Accesorios accesorios;
	private Date fechaCompra;
	private Date fechaDevolucion;
	private String dniComprador;
	private String nombre;
	private String apellido1;
	private String apellido2;
	private String direccion;
	private String poblacion;
	private int telefono;
	private int cp;

	public Ventas() {
	}

	public Ventas(Empleados empleados, Accesorios accesorios, Date fechaCompra,
			String dniComprador, String nombre, String apellido1,
			String apellido2, String direccion, String poblacion, int telefono,
			int cp) {
		this.empleados = empleados;
		this.accesorios = accesorios;
		this.fechaCompra = fechaCompra;
		this.dniComprador = dniComprador;
		this.nombre = nombre;
		this.apellido1 = apellido1;
		this.apellido2 = apellido2;
		this.direccion = direccion;
		this.poblacion = poblacion;
		this.telefono = telefono;
		this.cp = cp;
	}

	public Ventas(Empleados empleados, Accesorios accesorios, Date fechaCompra,
			Date fechaDevolucion, String dniComprador, String nombre,
			String apellido1, String apellido2, String direccion,
			String poblacion, int telefono, int cp) {
		this.empleados = empleados;
		this.accesorios = accesorios;
		this.fechaCompra = fechaCompra;
		this.fechaDevolucion = fechaDevolucion;
		this.dniComprador = dniComprador;
		this.nombre = nombre;
		this.apellido1 = apellido1;
		this.apellido2 = apellido2;
		this.direccion = direccion;
		this.poblacion = poblacion;
		this.telefono = telefono;
		this.cp = cp;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Empleados getEmpleados() {
		return this.empleados;
	}

	public void setEmpleados(Empleados empleados) {
		this.empleados = empleados;
	}

	public Accesorios getAccesorios() {
		return this.accesorios;
	}

	public void setAccesorios(Accesorios accesorios) {
		this.accesorios = accesorios;
	}

	public Date getFechaCompra() {
		return this.fechaCompra;
	}

	public void setFechaCompra(Date fechaCompra) {
		this.fechaCompra = fechaCompra;
	}

	public Date getFechaDevolucion() {
		return this.fechaDevolucion;
	}

	public void setFechaDevolucion(Date fechaDevolucion) {
		this.fechaDevolucion = fechaDevolucion;
	}

	public String getDniComprador() {
		return this.dniComprador;
	}

	public void setDniComprador(String dniComprador) {
		this.dniComprador = dniComprador;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellido1() {
		return this.apellido1;
	}

	public void setApellido1(String apellido1) {
		this.apellido1 = apellido1;
	}

	public String getApellido2() {
		return this.apellido2;
	}

	public void setApellido2(String apellido2) {
		this.apellido2 = apellido2;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getPoblacion() {
		return this.poblacion;
	}

	public void setPoblacion(String poblacion) {
		this.poblacion = poblacion;
	}

	public int getTelefono() {
		return this.telefono;
	}

	public void setTelefono(int telefono) {
		this.telefono = telefono;
	}

	public int getCp() {
		return this.cp;
	}

	public void setCp(int cp) {
		this.cp = cp;
	}

}
